### PR TITLE
[Improve][docs] Add new committers

### PR DESCRIPTION
**Pull request by TyrantLucifer**
Add new committers' information.

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Hi @Hisoka-X PTAL.

**Comment by Hisoka-X** [comment]
Hi, please add [gaojun2048](https://whimsy.apache.org/roster/committer/gaojun2048)

**Comment by TyrantLucifer** [comment]
> Hi, please add [gaojun2048](https://whimsy.apache.org/roster/committer/gaojun2048), match with https://whimsy.apache.org/roster/ppmc/seatunnel

Done

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
