### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by lhyundeadsoul**
`job manager ` -> `task manager`

### CODE REVIEW

**Comment by lhyundeadsoul** [comment]
@Hisoka-X can you help to review?

**Comment by Hisoka-X** [comment]
> @Hisoka-X can you help to review?

Hi, I find so many file have change or update, but I can't find what do you had changed, maybe you should create new fork from seatunnel-website(Or rebase from old commit, then pull again), then commit list will only show what changed by yourself.  And Because you had change index.html, can you upload some picture to show what different between before and after. Thanks!

**Comment by lhyundeadsoul** [comment]
> > @Hisoka-X can you help to review?
> 
> Hi, I find so many file have change or update, but I can't find what do you had changed, maybe you should create new fork from seatunnel-website(Or rebase from old commit, then pull again), then commit list will only show what changed by yourself. And Because you had change index.html, can you upload some picture to show what different between before and after. Thanks!

I'm so sorry for this. It's rebase problem.  I will fix this soon. Sorry again.

**Comment by lhyundeadsoul** [comment]
PTAL  https://github.com/apache/incubator-seatunnel-website/pull/132 @Hisoka-X

**Pull request closed without merging**
