### PR TITLE
[Feature] add user cases module

### PR DESCRIPTION
**Pull request by zhuangchong**
add user cases module

iShot2022-04-11 17 41 44
iShot2022-04-11 17 40 58

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
Well done

**Comment by CalvinKirs** [comment]
@zhongjiajie Hi,PTAL thx:)

**Comment by zhuangchong** [comment]
> Is it a little confusing about `user case` and `users`? They are a little duplicate

What would it be better to change to?  `ApplicationCases` and `Users` ?

**Comment by zhongjiajie** [comment]
IMO, I prefer to add user cases as hyperlinks under our users. I think it makes more sense than in separate pages
image

Or maybe use the carousel at the bottom of the page https://seatunnel.apache.org/user, because we do not have all our user's cases.

**Comment by zhuangchong** [comment]
@CalvinKirs @zhongjiajie 
I suggest using the second method. Next, I try to modify it, but I can't say that I can make this effect. If there are other small partners who are willing to realize it, you can reply to claim it.

**Comment by zhongjiajie** [comment]
> @CalvinKirs @zhongjiajie I suggest using the second method. Next, I try to modify it, but I can't say that I can make this effect. If there are other small partners who are willing to realize it, you can reply to claim it.

Thanks kerwin!

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
