### PR TITLE
Asf site

### PR DESCRIPTION
**Pull request by xvm03**
fix the quick start link

### CODE REVIEW

**Review by zhongjiajie — COMMENTED** [review]
Good catch, I search pattern `https://seatunnel.apache.org/docs/` globally, and find there are still some context in `versioned_docs/version-2.1.0/flink/configuration/ConfigExamples.md` should be added version, do you have time to change it too?

**Comment by wuchunfu** [comment]
@zhongjiajie @xvm03 I think if I want to modify it should be the `main` branch `2.1.0` docs, not the `asf-site` branch

**Comment by zhongjiajie** [comment]
🤣 You're right, I do not find out this before. Thanks for your clarification

**Comment by zhongjiajie** [comment]
??

**Comment by zhongjiajie** [comment]
Hi @xvm03 I do not know why , but when I  change you target branch from `asf-site` to `main` this PR auto close and can not reopen anymore. Could you try to submit another PR? So sorry about that

**Pull request closed without merging**
