### PR TITLE
[Feature]The blog module supports Chinese and English

### PR DESCRIPTION
**Pull request by zhuangchong**
The blog module supports Chinese and English

iShot2022-02-18 19 04 59

### CODE REVIEW

**Comment by CalvinKirs** [comment]
hi, there is a problem with switching between Chinese and English

**Comment by CalvinKirs** [comment]
image

**Comment by zhuangchong** [comment]
@CalvinKirs 
Updated, please review

iShot2022-02-18 21 21 47
iShot2022-02-18 21 21 02

**Review by CalvinKirs — APPROVED** [review]
well done

**Pull request merged**
